### ISSUE TITLE
need example of evaluate MMRR

### ISSUE THREAD

**Issue by Georgepitt** [DeepSoftwareAnalytics/CoSQA_Plus#1]
你好。请问这个evaluate MMRR的评测脚本有使用示范，和示例输出吗？能否提供一个readme.md

**Comment by thinkerhui** [comment]
感谢关注CoSQA+，我们有新的README。由于最近比较忙，README.md没有及时更新😂

**Comment by thinkerhui** [comment]
> 你好。请问这个evaluate MMRR的评测脚本有使用示范，和示例输出吗？能否提供一个readme.md

现在已经更新了README，同时仓库的结构也进行了优化。

**Comment by CZH-THU** [comment]
select_code.py", line 48, in convert_query_examples_to_features
    nl = (" ".join(js["doc"].split()))
                   ~~^^^^^^^
KeyError: 'doc'
 用的google drive里的数据，但是报错 query.json，没有‘doc’key
